// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: Admin.sql

package dto

import (
	"context"
	"database/sql"
)

const createAdmin = `-- name: CreateAdmin :execresult
INSERT INTO Administrador (nombre, correo, usuario, contraseña)
VALUES (?, ?, ?, ?)
`

type CreateAdminParams struct {
	Nombre     string `json:"nombre"`
	Correo     string `json:"correo"`
	Usuario    string `json:"usuario"`
	Contraseña string `json:"contraseña"`
}

func (q *Queries) CreateAdmin(ctx context.Context, arg CreateAdminParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createAdmin,
		arg.Nombre,
		arg.Correo,
		arg.Usuario,
		arg.Contraseña,
	)
}

const deleteAdmin = `-- name: DeleteAdmin :execresult
DELETE FROM Administrador WHERE idAdministrador = ?
`

func (q *Queries) DeleteAdmin(ctx context.Context, idadministrador int32) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteAdmin, idadministrador)
}

const deleteAdminByName = `-- name: DeleteAdminByName :execresult
DELETE FROM Administrador WHERE nombre = ?
`

func (q *Queries) DeleteAdminByName(ctx context.Context, nombre string) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteAdminByName, nombre)
}

const getAdminById = `-- name: GetAdminById :one
SELECT idAdministrador, nombre, correo, usuario
 FROM Administrador WHERE idAdministrador = ? LIMIT 1
`

type GetAdminByIdRow struct {
	Idadministrador int32  `json:"idadministrador"`
	Nombre          string `json:"nombre"`
	Correo          string `json:"correo"`
	Usuario         string `json:"usuario"`
}

func (q *Queries) GetAdminById(ctx context.Context, idadministrador int32) (GetAdminByIdRow, error) {
	row := q.db.QueryRowContext(ctx, getAdminById, idadministrador)
	var i GetAdminByIdRow
	err := row.Scan(
		&i.Idadministrador,
		&i.Nombre,
		&i.Correo,
		&i.Usuario,
	)
	return i, err
}

const getAdminByName = `-- name: GetAdminByName :one
SELECT idAdministrador, nombre, correo, usuario 
FROM Administrador WHERE nombre = ? LIMIT 1
`

type GetAdminByNameRow struct {
	Idadministrador int32  `json:"idadministrador"`
	Nombre          string `json:"nombre"`
	Correo          string `json:"correo"`
	Usuario         string `json:"usuario"`
}

func (q *Queries) GetAdminByName(ctx context.Context, nombre string) (GetAdminByNameRow, error) {
	row := q.db.QueryRowContext(ctx, getAdminByName, nombre)
	var i GetAdminByNameRow
	err := row.Scan(
		&i.Idadministrador,
		&i.Nombre,
		&i.Correo,
		&i.Usuario,
	)
	return i, err
}

const getAllAdmins = `-- name: GetAllAdmins :many
SELECT idAdministrador, nombre, correo, usuario FROM Administrador
`

type GetAllAdminsRow struct {
	Idadministrador int32  `json:"idadministrador"`
	Nombre          string `json:"nombre"`
	Correo          string `json:"correo"`
	Usuario         string `json:"usuario"`
}

func (q *Queries) GetAllAdmins(ctx context.Context) ([]GetAllAdminsRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllAdmins)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllAdminsRow
	for rows.Next() {
		var i GetAllAdminsRow
		if err := rows.Scan(
			&i.Idadministrador,
			&i.Nombre,
			&i.Correo,
			&i.Usuario,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAdmin = `-- name: UpdateAdmin :execresult
UPDATE Administrador
SET nombre = ?, correo = ?, usuario = ? WHERE idAdministrador = ?
`

type UpdateAdminParams struct {
	Nombre          string `json:"nombre"`
	Correo          string `json:"correo"`
	Usuario         string `json:"usuario"`
	Idadministrador int32  `json:"idadministrador"`
}

func (q *Queries) UpdateAdmin(ctx context.Context, arg UpdateAdminParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateAdmin,
		arg.Nombre,
		arg.Correo,
		arg.Usuario,
		arg.Idadministrador,
	)
}

const updateAdminPassword = `-- name: UpdateAdminPassword :execresult
UPDATE Administrador SET contraseña = ? 
WHERE idAdministrador = ?
`

type UpdateAdminPasswordParams struct {
	Contraseña      string `json:"contraseña"`
	Idadministrador int32  `json:"idadministrador"`
}

func (q *Queries) UpdateAdminPassword(ctx context.Context, arg UpdateAdminPasswordParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateAdminPassword, arg.Contraseña, arg.Idadministrador)
}
