// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: Admin.sql

package dto

import (
	"context"
	"database/sql"
)

const createAdmin = `-- name: CreateAdmin :execresult
INSERT INTO Administrador (nombre)
VALUES (?)
`

func (q *Queries) CreateAdmin(ctx context.Context, nombre string) (sql.Result, error) {
	return q.db.ExecContext(ctx, createAdmin, nombre)
}

const deleteAdmin = `-- name: DeleteAdmin :execresult
DELETE FROM Administrador WHERE idAdministrador = ?
`

func (q *Queries) DeleteAdmin(ctx context.Context, idadministrador int32) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteAdmin, idadministrador)
}

const deleteAdminByName = `-- name: DeleteAdminByName :execresult
DELETE FROM Administrador WHERE nombre = ?
`

func (q *Queries) DeleteAdminByName(ctx context.Context, nombre string) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteAdminByName, nombre)
}

const getAdminById = `-- name: GetAdminById :one
SELECT idAdministrador, nombre
 FROM Administrador WHERE idAdministrador = ? LIMIT 1
`

func (q *Queries) GetAdminById(ctx context.Context, idadministrador int32) (Administrador, error) {
	row := q.db.QueryRowContext(ctx, getAdminById, idadministrador)
	var i Administrador
	err := row.Scan(&i.Idadministrador, &i.Nombre)
	return i, err
}

const getAdminByName = `-- name: GetAdminByName :one
SELECT idAdministrador, nombre 
FROM Administrador WHERE nombre = ? LIMIT 1
`

func (q *Queries) GetAdminByName(ctx context.Context, nombre string) (Administrador, error) {
	row := q.db.QueryRowContext(ctx, getAdminByName, nombre)
	var i Administrador
	err := row.Scan(&i.Idadministrador, &i.Nombre)
	return i, err
}

const getAllAdmins = `-- name: GetAllAdmins :many
SELECT idAdministrador, nombre FROM Administrador
`

func (q *Queries) GetAllAdmins(ctx context.Context) ([]Administrador, error) {
	rows, err := q.db.QueryContext(ctx, getAllAdmins)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Administrador
	for rows.Next() {
		var i Administrador
		if err := rows.Scan(&i.Idadministrador, &i.Nombre); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAdmin = `-- name: UpdateAdmin :execresult
UPDATE Administrador
SET nombre = ?
WHERE idAdministrador = ?
`

type UpdateAdminParams struct {
	Nombre          string `json:"nombre"`
	Idadministrador int32  `json:"idadministrador"`
}

func (q *Queries) UpdateAdmin(ctx context.Context, arg UpdateAdminParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateAdmin, arg.Nombre, arg.Idadministrador)
}
