// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: Client.sql

package dto

import (
	"context"
	"database/sql"
)

const createClient = `-- name: CreateClient :execresult
INSERT INTO Cliente (nombre, correo, usuario, contraseña)
VALUES (?, ?, ?, ?)
`

type CreateClientParams struct {
	Nombre     string `json:"nombre"`
	Correo     string `json:"correo"`
	Usuario    string `json:"usuario"`
	Contraseña string `json:"contraseña"`
}

func (q *Queries) CreateClient(ctx context.Context, arg CreateClientParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createClient,
		arg.Nombre,
		arg.Correo,
		arg.Usuario,
		arg.Contraseña,
	)
}

const deleteClient = `-- name: DeleteClient :exec
DELETE FROM Cliente WHERE idCliente = ?
`

func (q *Queries) DeleteClient(ctx context.Context, idcliente int32) error {
	_, err := q.db.ExecContext(ctx, deleteClient, idcliente)
	return err
}

const getAllClients = `-- name: GetAllClients :many
SELECT idcliente, nombre, correo, usuario, contraseña FROM Cliente
`

func (q *Queries) GetAllClients(ctx context.Context) ([]Cliente, error) {
	rows, err := q.db.QueryContext(ctx, getAllClients)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Cliente
	for rows.Next() {
		var i Cliente
		if err := rows.Scan(
			&i.Idcliente,
			&i.Nombre,
			&i.Correo,
			&i.Usuario,
			&i.Contraseña,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getClientById = `-- name: GetClientById :one
SELECT idcliente, nombre, correo, usuario, contraseña FROM Cliente WHERE idCliente = ? LIMIT 1
`

func (q *Queries) GetClientById(ctx context.Context, idcliente int32) (Cliente, error) {
	row := q.db.QueryRowContext(ctx, getClientById, idcliente)
	var i Cliente
	err := row.Scan(
		&i.Idcliente,
		&i.Nombre,
		&i.Correo,
		&i.Usuario,
		&i.Contraseña,
	)
	return i, err
}

const updateClient = `-- name: UpdateClient :exec
UPDATE Cliente
SET nombre = ?, correo = ?, usuario = ?
WHERE idCliente = ?
`

type UpdateClientParams struct {
	Nombre    string `json:"nombre"`
	Correo    string `json:"correo"`
	Usuario   string `json:"usuario"`
	Idcliente int32  `json:"idcliente"`
}

func (q *Queries) UpdateClient(ctx context.Context, arg UpdateClientParams) error {
	_, err := q.db.ExecContext(ctx, updateClient,
		arg.Nombre,
		arg.Correo,
		arg.Usuario,
		arg.Idcliente,
	)
	return err
}

const updateClientPassword = `-- name: updateClientPassword :exec
UPDATE Cliente SET contraseña = ? 
WHERE idCliente = ?
`

type updateClientPasswordParams struct {
	Contraseña string `json:"contraseña"`
	Idcliente  int32  `json:"idcliente"`
}

func (q *Queries) updateClientPassword(ctx context.Context, arg updateClientPasswordParams) error {
	_, err := q.db.ExecContext(ctx, updateClientPassword, arg.Contraseña, arg.Idcliente)
	return err
}
