// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: Client.sql

package dto

import (
	"context"
	"database/sql"
)

const createClient = `-- name: CreateClient :execresult
INSERT INTO Cliente (nombre)
VALUES (?)
`

func (q *Queries) CreateClient(ctx context.Context, nombre string) (sql.Result, error) {
	return q.db.ExecContext(ctx, createClient, nombre)
}

const deleteClient = `-- name: DeleteClient :execresult
DELETE FROM Cliente WHERE idCliente = ?
`

func (q *Queries) DeleteClient(ctx context.Context, idcliente int32) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteClient, idcliente)
}

const deleteClientByName = `-- name: DeleteClientByName :execresult
DELETE FROM Cliente WHERE nombre = ?
`

func (q *Queries) DeleteClientByName(ctx context.Context, nombre string) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteClientByName, nombre)
}

const getAllClients = `-- name: GetAllClients :many
SELECT idCliente, nombre FROM Cliente
`

type GetAllClientsRow struct {
	Idcliente int32  `json:"idcliente"`
	Nombre    string `json:"nombre"`
}

func (q *Queries) GetAllClients(ctx context.Context) ([]GetAllClientsRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllClients)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllClientsRow
	for rows.Next() {
		var i GetAllClientsRow
		if err := rows.Scan(&i.Idcliente, &i.Nombre); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getClientById = `-- name: GetClientById :one
SELECT idCliente, nombre
FROM Cliente WHERE idCliente = ? LIMIT 1
`

type GetClientByIdRow struct {
	Idcliente int32  `json:"idcliente"`
	Nombre    string `json:"nombre"`
}

func (q *Queries) GetClientById(ctx context.Context, idcliente int32) (GetClientByIdRow, error) {
	row := q.db.QueryRowContext(ctx, getClientById, idcliente)
	var i GetClientByIdRow
	err := row.Scan(&i.Idcliente, &i.Nombre)
	return i, err
}

const getClientByName = `-- name: GetClientByName :one
SELECT idCliente, nombre 
FROM Cliente WHERE nombre = ? LIMIT 1
`

type GetClientByNameRow struct {
	Idcliente int32  `json:"idcliente"`
	Nombre    string `json:"nombre"`
}

func (q *Queries) GetClientByName(ctx context.Context, nombre string) (GetClientByNameRow, error) {
	row := q.db.QueryRowContext(ctx, getClientByName, nombre)
	var i GetClientByNameRow
	err := row.Scan(&i.Idcliente, &i.Nombre)
	return i, err
}

const updateClient = `-- name: UpdateClient :execresult
UPDATE Cliente
SET nombre = ?
WHERE idCliente = ?
`

type UpdateClientParams struct {
	Nombre    string `json:"nombre"`
	Idcliente int32  `json:"idcliente"`
}

func (q *Queries) UpdateClient(ctx context.Context, arg UpdateClientParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateClient, arg.Nombre, arg.Idcliente)
}
