// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package dto

import (
	"database/sql"
	"time"
)

type Administrador struct {
	Idadministrador int32  `json:"idadministrador"`
	Nombre          string `json:"nombre"`
}

type Cliente struct {
	Idcliente int32  `json:"idcliente"`
	Nombre    string `json:"nombre"`
	Telefono  int32  `json:"telefono"`
}

type Detalleviaje struct {
	Iddetalleviaje int32         `json:"iddetalleviaje"`
	Fecha          time.Time     `json:"fecha"`
	Hora           time.Time     `json:"hora"`
	Idproveedor    sql.NullInt32 `json:"idproveedor"`
	Idviaje        int32         `json:"idviaje"`
}

type Proveedor struct {
	Idproveedor int32  `json:"idproveedor"`
	Nombre      string `json:"nombre"`
	Descrip     string `json:"descrip"`
}

type Reserva struct {
	Idreservas int32  `json:"idreservas"`
	Idusuario  int32  `json:"idusuario"`
	Iddetalle  int32  `json:"iddetalle"`
	Estado     string `json:"estado"`
}

type Usuario struct {
	Idusuario       int32          `json:"idusuario"`
	Correo          string         `json:"correo"`
	Usuario         string         `json:"usuario"`
	Contraseña      string         `json:"contraseña"`
	Role            string         `json:"role"`
	Img             sql.NullString `json:"img"`
	Idadministrador sql.NullInt32  `json:"idadministrador"`
	Idcliente       sql.NullInt32  `json:"idcliente"`
	CreatedAt       sql.NullTime   `json:"created_at"`
	UpdatedAt       sql.NullTime   `json:"updated_at"`
	RememberToken   sql.NullString `json:"remember_token"`
}

type Viaje struct {
	Idviaje     int32  `json:"idviaje"`
	Tipoviaje   string `json:"tipoviaje"`
	Descripcion string `json:"descripcion"`
}
