// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package dto

import (
	"database/sql"
	"time"
)

type Administrador struct {
	Idadministrador int32  `json:"idadministrador"`
	Nombre          string `json:"nombre"`
	Usuario         string `json:"usuario"`
	Contraseña      string `json:"contraseña"`
}

type Cliente struct {
	Idcliente  int32  `json:"idcliente"`
	Nombre     string `json:"nombre"`
	Correo     string `json:"correo"`
	Usuario    string `json:"usuario"`
	Contraseña string `json:"contraseña"`
}

type Detalleviaje struct {
	Iddetalleviaje int32         `json:"iddetalleviaje"`
	Tipoviaje      string        `json:"tipoviaje"`
	Idproveedor    sql.NullInt32 `json:"idproveedor"`
	Idviaje        int32         `json:"idviaje"`
}

type Historial struct {
	Idhistorial int32  `json:"idhistorial"`
	Descrip     string `json:"descrip"`
	Idcliente   int32  `json:"idcliente"`
	Idreserva   int32  `json:"idreserva"`
}

type Pasajero struct {
	Idpasajeros int32  `json:"idpasajeros"`
	Nombre      string `json:"nombre"`
	Edad        int32  `json:"edad"`
	Iddetalle   int32  `json:"iddetalle"`
}

type Proveedor struct {
	Idproveedor int32  `json:"idproveedor"`
	Nombre      string `json:"nombre"`
	Descrip     string `json:"descrip"`
}

type Reserva struct {
	Idreservas      int32 `json:"idreservas"`
	Idcliente       int32 `json:"idcliente"`
	Idadministrador int32 `json:"idadministrador"`
	Iddetalle       int32 `json:"iddetalle"`
}

type Telefonocliente struct {
	Idtelefonoclientes int32  `json:"idtelefonoclientes"`
	Numero             string `json:"numero"`
	Tipo               string `json:"tipo"`
	Idcliente          int32  `json:"idcliente"`
}

type Viaje struct {
	Idviaje int32     `json:"idviaje"`
	Fecha   time.Time `json:"fecha"`
	Hora    time.Time `json:"hora"`
}
