// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package dto

import (
	"database/sql"
	"time"
)

type Administrador struct {
	Idadministrador int32  `json:"idadministrador"`
	Nombre          string `json:"nombre"`
}

type Cliente struct {
	Idcliente int32  `json:"idcliente"`
	Nombre    string `json:"nombre"`
}

type Detalleviaje struct {
	Iddetalleviaje int32         `json:"iddetalleviaje"`
	Fecha          time.Time     `json:"fecha"`
	Hora           time.Time     `json:"hora"`
	Idproveedor    sql.NullInt32 `json:"idproveedor"`
	Idviaje        int32         `json:"idviaje"`
}

type Pasajero struct {
	Idpasajeros int32  `json:"idpasajeros"`
	Nombre      string `json:"nombre"`
	Edad        int32  `json:"edad"`
	Iddetalle   int32  `json:"iddetalle"`
}

type Proveedor struct {
	Idproveedor int32  `json:"idproveedor"`
	Nombre      string `json:"nombre"`
	Descrip     string `json:"descrip"`
}

type Reserva struct {
	Idreservas      int32 `json:"idreservas"`
	Idcliente       int32 `json:"idcliente"`
	Idadministrador int32 `json:"idadministrador"`
	Iddetalle       int32 `json:"iddetalle"`
}

type Telefonocliente struct {
	Idtelefonoclientes int32  `json:"idtelefonoclientes"`
	Numero             string `json:"numero"`
	Tipo               string `json:"tipo"`
	Idcliente          int32  `json:"idcliente"`
}

type Usuario struct {
	Idusuario       int32          `json:"idusuario"`
	Correo          string         `json:"correo"`
	Usuario         string         `json:"usuario"`
	Contraseña      string         `json:"contraseña"`
	Role            string         `json:"role"`
	Idadministrador sql.NullInt32  `json:"idadministrador"`
	Idcliente       sql.NullInt32  `json:"idcliente"`
	CreatedAt       sql.NullTime   `json:"created_at"`
	UpdatedAt       sql.NullTime   `json:"updated_at"`
	RememberToken   sql.NullString `json:"remember_token"`
}

type Viaje struct {
	Idviaje   int32  `json:"idviaje"`
	Tipoviaje string `json:"tipoviaje"`
}
