// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: Reservation.sql

package dto

import (
	"context"
	"database/sql"
)

const createReservation = `-- name: CreateReservation :execresult
INSERT INTO reservas (idUsuario, idDetalle, estado)
VALUES (?, ?, ?)
`

type CreateReservationParams struct {
	Idusuario int32  `json:"idusuario"`
	Iddetalle int32  `json:"iddetalle"`
	Estado    string `json:"estado"`
}

func (q *Queries) CreateReservation(ctx context.Context, arg CreateReservationParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createReservation, arg.Idusuario, arg.Iddetalle, arg.Estado)
}

const deleteReservation = `-- name: DeleteReservation :exec
DELETE FROM reservas WHERE idreservas = ?
`

func (q *Queries) DeleteReservation(ctx context.Context, idreservas int32) error {
	_, err := q.db.ExecContext(ctx, deleteReservation, idreservas)
	return err
}

const getAllReservations = `-- name: GetAllReservations :many
SELECT idreservas, idusuario, iddetalle, estado FROM reservas
`

func (q *Queries) GetAllReservations(ctx context.Context) ([]Reserva, error) {
	rows, err := q.db.QueryContext(ctx, getAllReservations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Reserva
	for rows.Next() {
		var i Reserva
		if err := rows.Scan(
			&i.Idreservas,
			&i.Idusuario,
			&i.Iddetalle,
			&i.Estado,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getReservationsById = `-- name: GetReservationsById :one
SELECT idreservas, idusuario, iddetalle, estado FROM reservas WHERE idreservas = ? LIMIT 1
`

func (q *Queries) GetReservationsById(ctx context.Context, idreservas int32) (Reserva, error) {
	row := q.db.QueryRowContext(ctx, getReservationsById, idreservas)
	var i Reserva
	err := row.Scan(
		&i.Idreservas,
		&i.Idusuario,
		&i.Iddetalle,
		&i.Estado,
	)
	return i, err
}

const updateReservation = `-- name: UpdateReservation :exec
UPDATE reservas
SET idUsuario = ?, idDetalle = ?
WHERE idreservas = ?
`

type UpdateReservationParams struct {
	Idusuario  int32 `json:"idusuario"`
	Iddetalle  int32 `json:"iddetalle"`
	Idreservas int32 `json:"idreservas"`
}

func (q *Queries) UpdateReservation(ctx context.Context, arg UpdateReservationParams) error {
	_, err := q.db.ExecContext(ctx, updateReservation, arg.Idusuario, arg.Iddetalle, arg.Idreservas)
	return err
}

const updateStatus = `-- name: UpdateStatus :exec
UPDATE reservas
SET estado = ?
WHERE idreservas = ?
`

type UpdateStatusParams struct {
	Estado     string `json:"estado"`
	Idreservas int32  `json:"idreservas"`
}

func (q *Queries) UpdateStatus(ctx context.Context, arg UpdateStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateStatus, arg.Estado, arg.Idreservas)
	return err
}
