// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: TravelDetail.sql

package dto

import (
	"context"
	"database/sql"
)

const createTravelDetail = `-- name: CreateTravelDetail :execresult
INSERT INTO detalleViaje (tipoViaje, idProveedor, idViaje)
VALUES (?, ?, ?)
`

type CreateTravelDetailParams struct {
	Tipoviaje   string        `json:"tipoviaje"`
	Idproveedor sql.NullInt32 `json:"idproveedor"`
	Idviaje     int32         `json:"idviaje"`
}

func (q *Queries) CreateTravelDetail(ctx context.Context, arg CreateTravelDetailParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createTravelDetail, arg.Tipoviaje, arg.Idproveedor, arg.Idviaje)
}

const deleteTravelDetail = `-- name: DeleteTravelDetail :exec
DELETE FROM detalleViaje WHERE iddetalleViaje = ?
`

func (q *Queries) DeleteTravelDetail(ctx context.Context, iddetalleviaje int32) error {
	_, err := q.db.ExecContext(ctx, deleteTravelDetail, iddetalleviaje)
	return err
}

const getAllTravelDetails = `-- name: GetAllTravelDetails :many
SELECT iddetalleviaje, tipoviaje, idproveedor, idviaje FROM detalleViaje
`

func (q *Queries) GetAllTravelDetails(ctx context.Context) ([]Detalleviaje, error) {
	rows, err := q.db.QueryContext(ctx, getAllTravelDetails)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Detalleviaje
	for rows.Next() {
		var i Detalleviaje
		if err := rows.Scan(
			&i.Iddetalleviaje,
			&i.Tipoviaje,
			&i.Idproveedor,
			&i.Idviaje,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTravelDetailById = `-- name: GetTravelDetailById :one
SELECT iddetalleviaje, tipoviaje, idproveedor, idviaje FROM detalleViaje WHERE iddetalleViaje = ? LIMIT 1
`

func (q *Queries) GetTravelDetailById(ctx context.Context, iddetalleviaje int32) (Detalleviaje, error) {
	row := q.db.QueryRowContext(ctx, getTravelDetailById, iddetalleviaje)
	var i Detalleviaje
	err := row.Scan(
		&i.Iddetalleviaje,
		&i.Tipoviaje,
		&i.Idproveedor,
		&i.Idviaje,
	)
	return i, err
}

const updateTravelDetail = `-- name: UpdateTravelDetail :exec
UPDATE detalleViaje
SET tipoViaje = ?, idProveedor = ?, idViaje = ?
WHERE iddetalleViaje = ?
`

type UpdateTravelDetailParams struct {
	Tipoviaje      string        `json:"tipoviaje"`
	Idproveedor    sql.NullInt32 `json:"idproveedor"`
	Idviaje        int32         `json:"idviaje"`
	Iddetalleviaje int32         `json:"iddetalleviaje"`
}

func (q *Queries) UpdateTravelDetail(ctx context.Context, arg UpdateTravelDetailParams) error {
	_, err := q.db.ExecContext(ctx, updateTravelDetail,
		arg.Tipoviaje,
		arg.Idproveedor,
		arg.Idviaje,
		arg.Iddetalleviaje,
	)
	return err
}
