drop TABLE Viaje;
drop TABLE detalleViaje;
drop TABLE telefonoClientes;
drop TABLE Pasajeros;
drop TABLE reservas;
drop TABLE Historial;
drop TABLE Proveedor;
drop TABLE Administrador;
drop TABLE Cliente;